### ISSUE TITLE
skinsrestorer integration doesn't work properly.

### ISSUE THREAD

**Issue by kgncengiz** [Cerothen/BlueMapSkinIntegration#3]
skinsrestorer integration doesn't work properly.

**Comment by Cerothen** [comment]
Can you be more specific? what about it isnt working properly? Does is error when loading? Does it show the wrong skin? What version of skinrestorer are you using (full version number)?

**Comment by kgncengiz** [comment]
my server runs on "Folia version git-Folia-24 (MC: 1.20.4)" I am using the latest version of skinsrestorer(v15.0.7) with a database and Bluemap is also up to date. when someone joins the world skin doesn't show up on the map without any errors or something else but it says "[BlueMapSkinIntegration] Checking SkinsRestorer"

**Comment by Cerothen** [comment]
The latest SkinsRestorer is 15.0.15 ( https://www.spigotmc.org/resources/skinsrestorer.2124/ ), The latest BlueMap is 5.2 ( https://github.com/BlueMap-Minecraft/BlueMap/releases ). I have never tried Folia, but since it adds multithreading officially it might cause some strange race condition.

> Folia won't be useful for the majority of servers out there and will break most public plugins. It's ideal for servers with very high players counts, that offer gamemodes that naturally spread players out, such as SkyBlock or SMP. [REFERENCE](https://papermc.io/software/folia)

I tested today with the above mentioned versions using my current Paper fork PURPUR (using the latest dev 1.21 build) which worked as expected. My current Mojang skin https://namemc.com/profile/Cerothen.1 was overridden by my skinsrestorer skin, as outlined in the check order for my config file.

```
providers:
  - skinsrestorer
  - mojang
#  - "dir:skins/{UUID}.png"
#  - "https://minotar.net/skin/{UUID}"

```

![Screenshot 2024-07-03 161735](https://github.com/Cerothen/BlueMapSkinIntegration/assets/9008757/565bf892-333b-489c-9e64-a585f760cc0c)

If your version is 15.0.7 I would consider updating to the actual latest version and try again.

**Comment by kgncengiz** [comment]
i am using skinsrestorer on the proxy mode which can be the cause of the problem.
